image: local_android

stages:
    - build

build_prd:
    stage: build
    only:
        - master
    script:
        - gradle clean test
        - gradle clean assembleRelease
        - curl $CURL_CREDENTIALS -T app/build/outputs/apk/release/app-release-unsigned.apk "https://binaries.artheriom.fr/artifactory/gradle-release-local/app/app-$(/root/fuck.sh).apk"
        - sonar-scanner $SONAR

build_dev:
    stage: build
    only:
        - develop
    script:
        - gradle clean test
        - gradle clean assembleDebug
        - sonar-scanner

test_all:
    stage: build
    except:
        - master
        - develop
    script:
        - gradle clean test