image: local_android

stages:
    - build

build_prd:
    stage: build
    only:
        - master
    script:
        - gradle clean test
        - gradle clean assembleRelease
        - cd app
        - sonar-scanner 
        - curl $CURL_CREDENTIALS -T app/build/outputs/apk/release/app-release-unsigned.apk "https://binaries.artheriom.fr/artifactory/gradle-release-local/app/app-$(/root/prod.sh).apk"

build_dev:
    stage: build
    only:
        - dev
    script:
        - gradle clean test
        - gradle clean assembleDebug
  #      - cd app
        - sonar-scanner
        - curl $CURL_CREDENTIALS -T app/build/outputs/apk/debug/app-debug.apk "https://binaries.artheriom.fr/artifactory/gradle-dev-local/app/app-$(/root/dev.sh).apk"

test_all:
    stage: build
    except:
        - master
        - dev
    script:
        - gradle clean test