image: local_android

stages:
    - build

build_prd:
    stage: build
    only:
        - master
    script:
        - gradle clean test
        - gradle clean assembleRelease

build_dev:
    stage: build
    only:
        - develop
    script:
        - gradle clean test
        - gradle clean assembleDebug
        
test_all:
    stage: build
    except:
        - master
        - develop
    script:
        - gradle clean test